language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
services:
  - postgresql
before_script:
  - psql -c 'create database test_health_check;' -U postgres
install:
  - pip install -r requirements.txt
script:
  - nosetests --with-coverage --cover-package=app
after_success:
  - coveralls